### ISSUE TITLE
Support immutable collections

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog-experimental#49]
I am using collections from `System.Collections.Immutable` (`ImmutableDictionary` in my case) and am getting the following exception:

```
System.Exception: Class System.Collections.Immutable.ImmutableDictionary`2[System.String,System.String] lacking an appropriate ctor

System.Exception
Class System.Collections.Immutable.ImmutableDictionary`2[System.String,System.String] lacking an appropriate ctor
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at Hedgehog.GenX.mkRandomMember@397-2.TypeShape-Core-Core-IMemberVisitor`2-Visit[b](ShapeMember`2 shape) in /home/runner/work/fsharp-hedgehog-experimental/fsharp-hedgehog-experimental/src/Hedgehog.Experimental/Gen.fs:line 400
   at Hedgehog.GenX.autoInner[a](AutoGenConfig config, FSharpMap`2 recursionDepths)
   at Hedgehog.GenX.autoInner@525-40.TypeShape-Core-Core-IConstructorVisitor`2-Visit[CtorParams](ShapeConstructor`2 ctor) in /home/runner/work/fsharp-hedgehog-experimental/fsharp-hedgehog-experimental/src/Hedgehog.Experimental/Gen.fs:line 528
   at InternalLogic.genxAutoBoxWith[T](AutoGenConfig x)
```

which points to [here](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/master/src/Hedgehog.Experimental/Gen.fs#L400)

Since immutable collections are part of BCL, it would be beneficial to support them.
Would it be possible to do?

**Comment by cmeeren** [comment]
Thanks for your feedback!

I don't think the library should necessarily support all types or collections (immutable or otherwise) in the BCL. In my experience, they are still rarely used in F# development. I'm considering whether I would accept a PR to add built-in support for this type, but I'm hesitant, because why stop there? There are thousands of BCL types, and the line needs to be drawn somewhere. Since this library has existed for so long without anyone requesting built-in support for more types, I think the current set is likely to be a good balance.

Furthermore, it's almost trivial to [add support for whatever types you want](https://github.com/hedgehogqa/fsharp-hedgehog-experimental#auto-generation) using `addGenerator`, where you can supply a chosen generator. That functionality is intended for situations just like this (and when needing to override the generator for a supported type). And of course, you can, if you want, hide the configuration behind an alias of `auto` that applies your chosen config. Then, the code that calls `auto` does not change; it will be as if the library had built-in support of whatever you need. Does that work for you?

**Comment by AlexeyRaga** [comment]
> There are thousands of BCL types

I thought (maybe incorrectly) that auto generators are supported via reflection, not by actually implementing these thousands of BCL types. Under this assumption I (perhaps mistakenly) thought that immutable collections are not supported just because their reflection pattern is slightly different. So supporting them would mean supporting one more pattern, which would include many more types.

> Does that work for you?

Well, it will have to, I guess :)

**Comment by cmeeren** [comment]
> I thought (maybe incorrectly) that auto generators are supported via reflection, not by actually implementing these thousands of BCL types.

There is some reflection to it; as I understand it, it [should be able to generate anything with a public constructor](https://github.com/hedgehogqa/fsharp-hedgehog-experimental/blob/master/src/Hedgehog.Experimental/Gen.fs#L515-L533). `ImmutableDictionary` does not have public constructors; only static `Create` methods. That's why it isn't supported. :)
